services:
  flask_app:
    build: .
    container_name: flask_plate_detector
    restart: always
    ports:
      - "8001:5000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=production
      - CLOUDINARY_URL=cloudinary://748983295927676:f8g7nRIpCa-DjOiuP1QbP0YFiT4@dadvtny30
