services:
  flask_app:
    build: .
    container_name: flask_plate_detector
    ports:
      - "50051:50051"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=production
      # - MINIO_ENDPOINT=139.59.250.218:9000
      - MINIO_ENDPOINT=goparking.duckdns.org:9000
      - MINIO_ACCESS_KEY=1d1KqQif0abfpxQaxyy0
      - MINIO_SECRET_KEY=i9n4WD3PFSzc6XFZkow69UWV5dGx6bZbmMIjaNlU
    command: python -u src/grpc_server.py
