services:
  flask_app:
    build: .
    container_name: flask_plate_detector
    restart: always
    ports:
      - "8001:5000"
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=production
      - PYTHONPATH=/app
