services:
  grpc_app:
    build: .
    container_name: plate_detector
    ports:
      - "50051:50051"
    environment:
      - FLASK_APP=src.app
      - FLASK_ENV=development
      - MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=b8psyEWauoDjytZjizEz
      - MINIO_SECRET_KEY=LkGSk5JoldvbLK9t8NzFKkf8QtREV46F4s6jBz5h
    command: python -u src/grpc_server.py

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - MINIO_ROOT_USER=b8psyEWauoDjytZjizEz
  #     - MINIO_ROOT_PASSWORD=LkGSk5JoldvbLK9t8NzFKkf8QtREV46F4s6jBz5h
  #   command: server /data
